name: Feature Request
description: Suggest an idea for SubTracker-AI
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for SubTracker-AI!

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have also considered...
    validations:
      required: false

  - type: checkboxes
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the application would this feature affect?
      options:
        - label: Dashboard & Analytics
        - label: Subscription Management
        - label: Budget & Financial Planning
        - label: Notifications & Alerts
        - label: Data Import/Export
        - label: User Interface/Experience
        - label: Mobile Responsiveness
        - label: Performance & Optimization
        - label: Security & Privacy
        - label: API & Integrations

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information that might be helpful
